# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:51
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import profiles.models
import simplemde.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=100, populate_from='name', unique=True)),
                ('desc', simplemde.fields.SimpleMDEField(blank=True)),
                ('desc_safe', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=100, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, default=1, max_digits=5)),
                ('is_available', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('avatar', imagekit.models.fields.ProcessedImageField(upload_to=profiles.models.upload_avatar)),
                ('banned', models.BooleanField(default=False)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('banned_reason', models.TextField(blank=True)),
                ('english_level', models.CharField(blank=True, choices=[('N', 'Native'), ('E', 'Excellence'), ('R', 'Good Reading, Average Speaking'), ('G', 'Good Enough for Works')], max_length=1)),
                ('about', simplemde.fields.SimpleMDEField(blank=True)),
                ('about_safe', models.TextField(blank=True)),
                ('hardwares', models.ManyToManyField(blank=True, related_name='_profile_hardwares_+', to='profiles.Hardware')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=100, populate_from='name', unique=True)),
                ('desc', simplemde.fields.SimpleMDEField(blank=True)),
                ('desc_safe', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=100, populate_from='name', unique=True)),
                ('desc', simplemde.fields.SimpleMDEField(blank=True)),
                ('desc_safe', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=100, populate_from='name', unique=True)),
                ('desc', simplemde.fields.SimpleMDEField(blank=True)),
                ('desc_safe', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_point', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('started_since', models.DateField(blank=True, null=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.Technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='_profile_languages_+', to='profiles.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='softwares',
            field=models.ManyToManyField(blank=True, related_name='_profile_softwares_+', to='profiles.Software'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
