# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:18
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=profiles.models.upload_avatar),
        ),
    ]
