# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_technologymasteringlevel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technologymasteringlevel',
            unique_together=set([('user', 'technology')]),
        ),
    ]
