# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170402_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologymasteringlevel',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
