# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_technologymasteringlevel_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologymasteringlevel',
            name='activity',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Several days a week'), ('M', 'Several days a month'), ('S', 'Scattered')], max_length=1),
        ),
        migrations.AddField(
            model_name='technologymasteringlevel',
            name='involved_real_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technologymasteringlevel',
            name='year_exp',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
