# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170405_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hardwares',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='softwares',
        ),
        migrations.AddField(
            model_name='profile',
            name='hardware',
            field=models.ManyToManyField(blank=True, related_name='_profile_hardware_+', to='profiles.Hardware'),
        ),
        migrations.AddField(
            model_name='profile',
            name='software',
            field=models.ManyToManyField(blank=True, related_name='_profile_software_+', to='profiles.Software'),
        ),
    ]
