# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170405_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='english_level',
            field=models.CharField(blank=True, choices=[('N', 'Native'), ('E', 'Excellent'), ('R', 'Good Reading, Average Speaking'), ('G', 'Good Enough for Works')], db_index=True, max_length=1),
        ),
    ]
