# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20170405_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_ready',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
