# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='desc_safe',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='software',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='software',
            name='desc_safe',
        ),
        migrations.RemoveField(
            model_name='software',
            name='slug',
        ),
    ]
