# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ('-order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ('-order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ('-order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('-order', 'name'), 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='hardware',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='software',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
